#!/bin/bash
# Fixed apt-get update erros: Hash Sum mismatch delete cache
# From http://stackoverflow.com/questions/15505775/debian-apt-packages-hash-sum-mismatch

sudo apt-get clean
sudo rm -rf /var/lib/apt/lists/*
sudo apt-get clean
sudo apt-get update
sudo apt-get upgrade
