#!/bin/bash
# open dir fast
# 取长度：len=`echo “$1”|awk '{print length($0)}'`
# if 判断：if [[ "$１" =~ "abc" ]], bash才支持 [[ ,sh不行， 判断是否包含abc，不能用复制正则，如加正则符号^$等
if [ `expr "$1" : '^[a-z]$'` == 1 ]; then
	nautilus /media/"$1" > /dev/null 2>&1
else
	nautilus "$1" > /dev/null 2>&1
fi
