#!/bin/bash

# 一般我们写脚本默认用 /bin/bash, 支持语法更多。
# 之前 ubuntu 中的 /bin/sh 是软链到 /bin/bash，
# 后来 Ubuntu 6.10 将 /bin/sh 软链到 /bin/dash。dash 是鉴于 bash 过于复杂
# 有人把 ash 从 NetBSD 移植到 Linux 并更名为 dash（Debian Almquist Shell），
# 并建议将 /bin/sh 指向它，以获得更快的脚本执行速度。
# 
# == echo $VAR 与 echo "$VAR" 区别：没引号字符串合并为一行

# == 单引号和双引号区别：单引号中内容如果有空格会被当作命令来执行
# 
# == cat的另类用法
# cat << EOF
# EOF

# == 判断字符串是否包含子串的一种方法
# str="this is a string",
# [[ $str =~ "this" ]] && echo "\$str contains this" 
# [[ $str =~ "that" ]] || echo "\$str does NOT contain this"
# 用到了"[[" 判断命令和 "=~"正则式匹配符号

# echo $*

# COMMANDS=(suspend resume up halt ssh ssh-config)
# if [[ "$1"="hello" || "$1"="word" ]]; then
# 	echo "sdfsdf";
# fi

########################################################################
#=> 引用常用函数库
########################################################################
source "/home/hanson/CodeHub/SHELL/libs/bootstrap.sh"


for x in $@; do
    echo $x
done