#!/bin/bash
# Breif: 
#   write complicated code for displaying tmux status often get erros,
#   so create a small file to be convenient to be calling.
# 

########################################################################
#=> common libs
########################################################################
source "$HOME/CodeHub/SHELL/libs/bootstrap.sh"

ut=$(uptime | grep -o -e 'up[^,]*\?,' | tr -d ',' | sed 's/up\s*//')
ut="⌛ ${ut}"

lock=$(xset -q | grep Caps | awk '{print $4}')
[[ $lock == "on" ]] && lock="on" || lock="off"
lock="⌨  ${lock}"

case "$1" in
    winsign)
        echo "≡ "
        ;;
    uptime)
        echo $ut
        ;;
    capslock)
        echo $lock
        ;;
    mixed)
        echo "${lock} ${ut}"
        ;;
    *) echo "NONE"
esac
