#!/bin/bash
# Breif: 
#   tmux run-shell action exec complicate command cause chaos.
#   maybe is the command str contains some specail char like (`"'),
#   it seems like the command would be cache.
# 

########################################################################
#=> common libs
########################################################################
source "$HOME/CodeHub/SHELL/libs/bootstrap.sh"

case "$1" in
    lastwindow)
        tmux select-window -t `tmux list-windows | sed -n '$p' | awk -F ':' '{print $1}'`
        ;;
    getactivewindow)
        tmux list-windows | egrep -o ' \w+\* ' | tr -d '*' 
        ;;
    getwindowlist)
        tmux lsw | percol --initial-index $(tmux lsw | awk '/ .+-/ {print NR-1}') \
                 | cut -d':' -f 1 | tr -d '\n' | xargs -0 tmux select-window -t
        ;;
    getsessionlist)
        tmux ls | percol --initial-index $(tmux ls | awk '/attached/ {print NR-1}') \
                | cut -d':' -f 1 | tr -d '\n' | xargs -0 tmux switch-client -t
        ;;
    copy)
        tmux save-buffer - | xsel -ib
        ;;
    paste)
        tmux set-buffer "$(xsel -ob)"; tmux paste-buffer
        ;;
    clear)
        xdotool set_window -name ' ' $(xdotool getactivewindow) && clear && tmux clear-history
        ;;
    *) echo "NONE" ;;
esac
