#!/bin/bash
# Purpose:
#   About Eclipse 
#   modify the tooltip_bg_color, tooltip_fg_color, left eclipse's tooltip show well
#

source "/home/hanson/CodeHub/SHELL/libs/bootstrap.sh"

COVER_COLOR=0
BG_COLOR=FG_COLOR=BG_COLOR_NEW=FG_COLOR_NEW=

# smart check
if cat /usr/share/themes/Ambiance/gtk-3.0/gtk-main.css|grep -i "tooltip_bg_color #000000" &>/dev/null; then
    COVER_COLOR=1
fi

if [[ $COVER_COLOR == 1 ]]; then
	BG_COLOR=#000000
	FG_COLOR=#FFFFFF
    BG_COLOR_NEW=#414141
    FG_COLOR_NEW=#FFFFFF
else
    BG_COLOR=#414141
    FG_COLOR=#FFFFFF
	BG_COLOR_NEW=#000000
	FG_COLOR_NEW=#FFFFFF
fi

sed -i -e "s/tooltip_bg_color ${BG_COLOR}/tooltip_bg_color ${BG_COLOR_NEW}/i" \
       -e "s/tooltip_fg_color ${FG_COLOR}/tooltip_fg_color ${FG_COLOR_NEW}/i" \
       /usr/share/themes/Ambiance/gtk-3.0/gtk-main.css

sed -i -e "s/tooltip_bg_color:${BG_COLOR}/tooltip_bg_color:${BG_COLOR_NEW}/i" \
       -e "s/tooltip_fg_color:${FG_COLOR}/tooltip_fg_color:${FG_COLOR_NEW}/i" \
       /usr/share/themes/Ambiance/gtk-2.0/gtkrc \
       /usr/share/themes/Ambiance/gtk-3.0/settings.ini

