#!/bin/bash
# vim: fdm=marker ts=4 sw=4 sts=4 expandtab

filename="$1"
target="$filename"
shift
for tag in "$@" ; do
    if grep -q '{.*}' <<< "$filename"; then
        tags=$(echo "$filename" | grep -o '{.*}')
        tags=$(echo "$tags" | sed -e "s/#$tag\b\s*//g" -e "s/\s*}/}/")
        if [[ $tags == "{}" ]]; then
            tags=""
        else
            tags=" $tags"
        fi
        tfilename=$(echo "$filename" | sed 's/\s*{.*}//')
    else
        tags=""
        tfilename="$filename"
    fi
    nfilename=$(echo "$tfilename" | sed "s/\(.[A-Za-z0-9]\+\)$/$tags\1/")
    filename="$nfilename"
done
mv "$target" "$nfilename"
