#!/bin/bash

########################################################################
#=> common libs
########################################################################
source "$HOME/CodeHub/SHELL/libs/bootstrap.sh"

HELP_MESSAGE="
Video combine easily with ffmpeg.
usage: 
  video-combine filename ... outputfile
  
  -h | --help   Show help message

"

#=> Show help
if [[ -z "$1" || "$1" == "--help" || "$1" == "-h" ]]; then
    helpShow
fi

#=> Main code
TEMPFILE="/tmp/"$(randchar)
OUTPUTFILE=${!#}
# FILEEXT="${OUTPUTFILE##*.}"
# [[ "$FILEEXT" == "$OUTPUTFILE" ]] && FILEEXT=''
if [[ $# < 3 ]]; then
    msg_error 'parames count must be over 2'
    exit 1
fi

# check files and write file list to tempfile
until [[ $# == 0 ]]; do
    FILE="$1"
    if [[ "$FILE" != "$OUTPUTFILE" ]]; then
        file_exists "$FILE"
        die_if_false $? "File does not exist"
        echo "file $PWD/$FILE" >> "$TEMPFILE"
    fi
    shift
done

# combine
ffmpeg -f concat -i "$TEMPFILE" -c copy "$OUTPUTFILE"

# delete the temp file
rm -f "$TEMPFILE"

